version: '3.8'

services:
  php:
    build: ./docker/php
    container_name: test-php-php
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./views:/var/www/html/views
      - ./config:/var/www/html/config
      - ./vendor:/var/www/html/vendor
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: test-php-nginx
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./vendor:/var/www/html/vendor
    ports:
      - "80:80"
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: test-php-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testphp
      MYSQL_USER: testuser
      MYSQL_PASSWORD: pass
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: test-php-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: testuser
      PMA_PASSWORD: pass
    depends_on:
      - mysql
    ports:
      - "81:80"