<?php

use App\DB\Migration;
use App\DB;

class InsertTableData extends Migration
{
    public function up()
    {
        // Вставка категорий (пример, часть дерева)
       DB::insert([
            ['id'=>2,'name'=>'Электроника','slug'=>'electronics','path'=>'1/2','description'=>'Гаджеты и техника','parent_id'=>1],
            ['id'=>3,'name'=>'Компьютеры','slug'=>'computers','path'=>'1/3','description'=>'ПК и комплектующие','parent_id'=>1],
            ['id'=>4,'name'=>'Бытовая техника','slug'=>'home-appliances','path'=>'1/4','description'=>'Техника для дома','parent_id'=>1],
            ['id'=>5,'name'=>'Товары для дома','slug'=>'home-goods','path'=>'1/5','description'=>'Все для дома','parent_id'=>1],
            ['id'=>6,'name'=>'Автотовары','slug'=>'auto','path'=>'1/6','description'=>'Все для автомобиля','parent_id'=>1],
            ['id'=>7,'name'=>'Спорт и отдых','slug'=>'sport','path'=>'1/7','description'=>'Товары для спорта','parent_id'=>1],

            ['id'=>8,'name'=>'Смартфоны','slug'=>'smartphones','path'=>'1/2/8','description'=>'Мобильные телефоны','parent_id'=>2],
            ['id'=>9,'name'=>'Планшеты','slug'=>'tablets','path'=>'1/2/9','description'=>'Планшетные устройства','parent_id'=>2],
            ['id'=>10,'name'=>'Телевизоры','slug'=>'tv','path'=>'1/2/10','description'=>'Телевизоры','parent_id'=>2],
            ['id'=>11,'name'=>'Аксессуары','slug'=>'electronics-accessories','path'=>'1/2/11','description'=>'Аксессуары для техники','parent_id'=>2],

            ['id'=>12,'name'=>'Android','slug'=>'android','path'=>'1/2/8/12','description'=>'Телефоны Android','parent_id'=>8],
            ['id'=>13,'name'=>'iPhone','slug'=>'iphone','path'=>'1/2/8/13','description'=>'Телефоны Apple','parent_id'=>8],
            ['id'=>14,'name'=>'Кнопочные','slug'=>'feature-phones','path'=>'1/2/8/14','description'=>'Кнопочные телефоны','parent_id'=>8],

            ['id'=>15,'name'=>'Samsung','slug'=>'samsung','path'=>'1/2/8/12/15','description'=>'Samsung телефоны','parent_id'=>12],
            ['id'=>16,'name'=>'Xiaomi','slug'=>'xiaomi','path'=>'1/2/8/12/16','description'=>'Xiaomi телефоны','parent_id'=>12],

            ['id'=>17,'name'=>'Ноутбуки','slug'=>'laptops','path'=>'1/3/17','description'=>'Портативные компьютеры','parent_id'=>3],
            ['id'=>18,'name'=>'Стационарные ПК','slug'=>'desktop','path'=>'1/3/18','description'=>'Настольные ПК','parent_id'=>3],
            ['id'=>19,'name'=>'Комплектующие','slug'=>'components','path'=>'1/3/19','description'=>'Запчасти','parent_id'=>3],
            ['id'=>20,'name'=>'Мониторы','slug'=>'monitors','path'=>'1/3/20','description'=>'Мониторы','parent_id'=>3],

            ['id'=>21,'name'=>'Игровые ноутбуки','slug'=>'gaming-laptops','path'=>'1/3/17/21','description'=>'Ноутбуки для игр','parent_id'=>17],
            ['id'=>22,'name'=>'Ультрабуки','slug'=>'ultrabooks','path'=>'1/3/17/22','description'=>'Тонкие ноутбуки','parent_id'=>17],

            ['id'=>23,'name'=>'Видеокарты','slug'=>'gpu','path'=>'1/3/19/23','description'=>'GPU','parent_id'=>19],
            ['id'=>24,'name'=>'Процессоры','slug'=>'cpu','path'=>'1/3/19/24','description'=>'CPU','parent_id'=>19],
            ['id'=>25,'name'=>'Материнские платы','slug'=>'motherboards','path'=>'1/3/19/25','description'=>'Motherboards','parent_id'=>19],

            ['id'=>26,'name'=>'Холодильники','slug'=>'fridges','path'=>'1/4/26','description'=>'Холодильники','parent_id'=>4],
            ['id'=>27,'name'=>'Стиральные машины','slug'=>'washers','path'=>'1/4/27','description'=>'Стиральные машины','parent_id'=>4],
            ['id'=>28,'name'=>'Микроволновки','slug'=>'microwaves','path'=>'1/4/28','description'=>'Микроволновки','parent_id'=>4],
            ['id'=>29,'name'=>'Пылесосы','slug'=>'vacuum','path'=>'1/4/29','description'=>'Пылесосы','parent_id'=>4],

            ['id'=>30,'name'=>'Мебель','slug'=>'furniture','path'=>'1/5/30','description'=>'Домашняя мебель','parent_id'=>5],
            ['id'=>31,'name'=>'Освещение','slug'=>'lighting','path'=>'1/5/31','description'=>'Лампы и свет','parent_id'=>5],
            ['id'=>32,'name'=>'Декор','slug'=>'decor','path'=>'1/5/32','description'=>'Украшения дома','parent_id'=>5],

            ['id'=>33,'name'=>'Шины','slug'=>'tires','path'=>'1/6/33','description'=>'Автомобильные шины','parent_id'=>6],
            ['id'=>34,'name'=>'Масла','slug'=>'oil','path'=>'1/6/34','description'=>'Моторные масла','parent_id'=>6],
            ['id'=>35,'name'=>'Аксессуары авто','slug'=>'auto-accessories','path'=>'1/6/35','description'=>'Аксессуары для авто','parent_id'=>6],

            ['id'=>36,'name'=>'Велосипеды','slug'=>'bikes','path'=>'1/7/36','description'=>'Велосипеды','parent_id'=>7],
            ['id'=>37,'name'=>'Тренажеры','slug'=>'fitness','path'=>'1/7/37','description'=>'Фитнес','parent_id'=>7],
            ['id'=>38,'name'=>'Туризм','slug'=>'tourism','path'=>'1/7/38','description'=>'Туристическое оборудование','parent_id'=>7],
            ['id'=>39,'name'=>'Кроссовки','slug'=>'sneakers','path'=>'1/7/39','description'=>'Обувь для спорта','parent_id'=>7],
            ['id'=>40,'name'=>'Футболки','slug'=>'t-shirts','path'=>'1/7/40','description'=>'Спортивные футболки','parent_id'=>7],
            ['id'=>41,'name'=>'Джинсы','slug'=>'jeans','path'=>'1/7/41','description'=>'Спортивные джинсы','parent_id'=>7],

            ['id'=>42,'name'=>'Кухонная техника','slug'=>'kitchen-appliances','path'=>'1/4/42','description'=>'Мелкая бытовая техника','parent_id'=>4],
            ['id'=>43,'name'=>'Утюги','slug'=>'irons','path'=>'1/4/43','description'=>'Для глажки','parent_id'=>4],
            ['id'=>44,'name'=>'Кофеварки','slug'=>'coffee-machines','path'=>'1/4/44','description'=>'Кофемашины','parent_id'=>4],
            ['id'=>45,'name'=>'Телевизионные приставки','slug'=>'tv-box','path'=>'1/2/45','description'=>'Приставки для ТВ','parent_id'=>2],
            ['id'=>46,'name'=>'Наушники','slug'=>'headphones','path'=>'1/2/46','description'=>'Для музыки и звонков','parent_id'=>2],
            ['id'=>47,'name'=>'Смарт-часы','slug'=>'smartwatch','path'=>'1/2/47','description'=>'Носимые устройства','parent_id'=>2],
            ['id'=>48,'name'=>'Клавиатуры','slug'=>'keyboards','path'=>'1/3/48','description'=>'Для компьютеров','parent_id'=>3],
            ['id'=>49,'name'=>'Мыши','slug'=>'mice','path'=>'1/3/49','description'=>'Компьютерные мыши','parent_id'=>3],
            ['id'=>50,'name'=>'Системные блоки','slug'=>'pc-cases','path'=>'1/3/50','description'=>'Корпуса ПК','parent_id'=>3],
            ['id'=>51,'name'=>'Планшеты','slug'=>'tablets','path'=>'1/3/51','description'=>'Планшетные ПК','parent_id'=>3],
            ['id'=>52,'name'=>'iPad','slug'=>'ipad','path'=>'1/51/52','description'=>'Apple iPad','parent_id'=>51],
            ['id'=>53,'name'=>'Android планшеты','slug'=>'android-tablets','path'=>'1/51/53','description'=>'Планшеты на Android','parent_id'=>51],
            ['id'=>54,'name'=>'Мобильные телефоны','slug'=>'mobiles','path'=>'1/2/54','description'=>'Смартфоны всех брендов','parent_id'=>2],
            ['id'=>55,'name'=>'Настольные ПК','slug'=>'desktop-pc','path'=>'1/3/55','description'=>'Стационарные компьютеры','parent_id'=>3],
            ['id'=>56,'name'=>'Ноутбуки','slug'=>'laptops','path'=>'1/3/56','description'=>'Ноутбуки всех брендов','parent_id'=>3],
            ['id'=>57,'name'=>'Комплектующие','slug'=>'components','path'=>'1/3/57','description'=>'Запчасти для ПК','parent_id'=>3],
            ['id'=>58,'name'=>'Видеокарты','slug'=>'video-cards','path'=>'1/57/58','description'=>'Графические карты','parent_id'=>57],
            ['id'=>59,'name'=>'Asus','slug'=>'asus','path'=>'1/58/59','description'=>'Asus видеокарты','parent_id'=>58],
            ['id'=>60,'name'=>'MSI','slug'=>'msi','path'=>'1/58/60','description'=>'MSI видеокарты','parent_id'=>58],
            ['id'=>61,'name'=>'Процессоры','slug'=>'cpus','path'=>'1/57/61','description'=>'Процессоры для ПК','parent_id'=>57],
            ['id'=>62,'name'=>'Материнские платы','slug'=>'motherboards','path'=>'1/57/62','description'=>'Материнские платы','parent_id'=>57],
            ['id'=>63,'name'=>'Оперативная память','slug'=>'ram','path'=>'1/57/63','description'=>'ОЗУ для ПК','parent_id'=>57],
            ['id'=>64,'name'=>'Накопители','slug'=>'storage','path'=>'1/57/64','description'=>'SSD и HDD','parent_id'=>57],
            ['id'=>65,'name'=>'Мониторы','slug'=>'monitors','path'=>'1/3/65','description'=>'Мониторы для ПК','parent_id'=>3],
            ['id'=>66,'name'=>'Ноутбуки Dell','slug'=>'dell-laptops','path'=>'1/56/66','description'=>'Ноутбуки Dell','parent_id'=>56],
            ['id'=>67,'name'=>'Ноутбуки HP','slug'=>'hp-laptops','path'=>'1/56/67','description'=>'Ноутбуки HP','parent_id'=>56],
            ['id'=>68,'name'=>'Ноутбуки Lenovo','slug'=>'lenovo-laptops','path'=>'1/56/68','description'=>'Ноутбуки Lenovo','parent_id'=>56],
            ['id'=>69,'name'=>'Ноутбуки Asus','slug'=>'asus-laptops','path'=>'1/56/69','description'=>'Ноутбуки Asus','parent_id'=>56],
            ['id'=>70,'name'=>'Смартфоны Samsung','slug'=>'samsung-phones','path'=>'1/54/70','description'=>'Смартфоны Samsung','parent_id'=>54],
            ['id'=>71,'name'=>'Смартфоны Apple','slug'=>'apple-phones','path'=>'1/54/71','description'=>'iPhone','parent_id'=>54],
            ['id'=>72,'name'=>'Смартфоны Xiaomi','slug'=>'xiaomi-phones','path'=>'1/54/72','description'=>'Xiaomi смартфоны','parent_id'=>54],
            ['id'=>73,'name'=>'Фитнес-браслеты','slug'=>'fitness-bands','path'=>'1/47/73','description'=>'Фитнес-трекеры','parent_id'=>47],
            ['id'=>74,'name'=>'Смарт-часы Apple','slug'=>'apple-watch','path'=>'1/47/74','description'=>'Apple Watch','parent_id'=>47],
            ['id'=>75,'name'=>'Смарт-часы Samsung','slug'=>'samsung-watch','path'=>'1/47/75','description'=>'Samsung Watch','parent_id'=>47],
            ['id'=>76,'name'=>'Периферия','slug'=>'peripherals','path'=>'1/3/76','description'=>'Клавиатуры, мыши, гарнитуры','parent_id'=>3],
            ['id'=>77,'name'=>'Гарнитуры','slug'=>'headsets','path'=>'1/76/77','description'=>'Наушники и микрофоны','parent_id'=>76],
            ['id'=>78,'name'=>'Веб-камеры','slug'=>'webcams','path'=>'1/76/78','description'=>'Для видеозвонков','parent_id'=>76],
            ['id'=>79,'name'=>'Сетевое оборудование','slug'=>'networking','path'=>'1/3/79','description'=>'Роутеры, свитчи','parent_id'=>3],
            ['id'=>80,'name'=>'Роутеры','slug'=>'routers','path'=>'1/79/80','description'=>'WiFi роутеры','parent_id'=>79],
            ['id'=>81,'name'=>'Свичи','slug'=>'switches','path'=>'1/79/81','description'=>'Коммутаторы','parent_id'=>79],
            ['id'=>82,'name'=>'Бытовая техника: Крупная','slug'=>'home-appliances-large','path'=>'1/42/82','description'=>'Холодильники, стиральные машины','parent_id'=>42],
            ['id'=>83,'name'=>'Электронные книги','slug'=>'e-books','path'=>'1/2/83','description'=>'E-readers и книги','parent_id'=>82],
            ['id'=>84,'name'=>'Стиральные машины 2','slug'=>'washing-machines2','path'=>'1/82/84','description'=>'Автоматические стиральные машины','parent_id'=>82],
            ['id'=>85,'name'=>'Мелкая бытовая техника: Кухня','slug'=>'small-kitchen-appliances','path'=>'1/42/85','description'=>'Блендеры, тостеры, кофемашины','parent_id'=>42],
            ['id'=>86,'name'=>'Блендеры','slug'=>'blenders','path'=>'1/85/86','description'=>'Кухонные блендеры','parent_id'=>85],
            ['id'=>87,'name'=>'Тостеры','slug'=>'toasters','path'=>'1/85/87','description'=>'Тостеры для хлеба','parent_id'=>85],
            ['id'=>88,'name'=>'Кофемашины','slug'=>'coffee-machines-small','path'=>'1/85/88','description'=>'Кофемашины для дома','parent_id'=>85],
            ['id'=>89,'name'=>'Игровые приставки','slug'=>'game-consoles','path'=>'1/45/89','description'=>'PlayStation, Xbox','parent_id'=>45],
            ['id'=>90,'name'=>'PlayStation','slug'=>'playstation','path'=>'1/89/90','description'=>'Sony PlayStation','parent_id'=>89],
            ['id'=>91,'name'=>'Xbox','slug'=>'xbox','path'=>'1/89/91','description'=>'Microsoft Xbox','parent_id'=>89],
            ['id'=>92,'name'=>'Nintendo','slug'=>'nintendo','path'=>'1/89/92','description'=>'Nintendo Switch','parent_id'=>89],
            ['id'=>93,'name'=>'Игровые аксессуары','slug'=>'game-accessories','path'=>'1/89/93','description'=>'Геймпады, джойстики','parent_id'=>89],
            ['id'=>94,'name'=>'Смарт-телевизоры','slug'=>'smart-tv','path'=>'1/2/94','description'=>'Телевизоры с функцией Smart','parent_id'=>2],
            ['id'=>95,'name'=>'Телевизоры LED','slug'=>'led-tv','path'=>'1/94/95','description'=>'LED телевизоры','parent_id'=>94],
            ['id'=>96,'name'=>'Телевизоры OLED','slug'=>'oled-tv','path'=>'1/94/96','description'=>'OLED телевизоры','parent_id'=>94],
            ['id'=>97,'name'=>'Проекторы','slug'=>'projectors','path'=>'1/2/97','description'=>'Проекторы для дома и офиса','parent_id'=>2],
            ['id'=>98,'name'=>'Акустика','slug'=>'acoustic','path'=>'1/2/98','description'=>'Колонки, саундбары','parent_id'=>2],
            ['id'=>99,'name'=>'Смарт-гаджеты','slug'=>'smart-gadgets','path'=>'1/2/99','description'=>'Разные умные устройства','parent_id'=>2]

        ])->into('categories')->exec();

        // products
        DB::insert([
            ['id'=>1,'name'=>'LG InstaView Door-in-Door','slug'=>'lg-instaview','description'=>'Современный холодильник с технологией InstaView и большим объёмом','price'=>'899.99'],
            ['id'=>2,'name'=>'Samsung Family Hub','slug'=>'samsung-family-hub','description'=>'Холодильник с сенсорным дисплеем и поддержкой умного дома','price'=>'1299.50'],
            ['id'=>3,'name'=>'Bosch Serie 6','slug'=>'bosch-serie-6','description'=>'Энергоэффективный холодильник с системой NoFrost','price'=>'749.00'],
            ['id'=>4,'name'=>'Whirlpool FreshZone','slug'=>'whirlpool-freshzone','description'=>'Холодильник с зоной свежести и низким уровнем шума','price'=>'680.25'],
            ['id'=>5,'name'=>'Electrolux TwinTech','slug'=>'electrolux-twintech','description'=>'Холодильник с технологией TwinTech и равномерным охлаждением','price'=>'820.40'],
            ['id'=>6,'name'=>'LG DoorCooling+','slug'=>'lg-doorcooling','description'=>'Холодильник с технологией DoorCooling+ и равномерным охлаждением','price'=>'770.00'],
            ['id'=>7,'name'=>'Samsung Bespoke','slug'=>'samsung-bespoke','description'=>'Модульный холодильник Bespoke с возможностью кастомизации','price'=>'1150.00'],
            ['id'=>8,'name'=>'Bosch VitaFresh','slug'=>'bosch-vitafresh','description'=>'Энергоэффективный холодильник с системой VitaFresh','price'=>'890.00'],
            ['id'=>9,'name'=>'Whirlpool NoFrost','slug'=>'whirlpool-nofrost','description'=>'Холодильник с системой NoFrost и низким уровнем шума','price'=>'720.00'],
            ['id'=>10,'name'=>'Electrolux Cooling 360','slug'=>'electrolux-cooling360','description'=>'Холодильник с технологией равномерного охлаждения Cooling 360','price'=>'950.00'],
            ['id'=>11,'name'=>'Haier MultiAirFlow','slug'=>'haier-multiairflow','description'=>'Холодильник с системой MultiAirFlow и большим объёмом','price'=>'680.00'],
            ['id'=>12,'name'=>'Gorenje NatureFresh','slug'=>'gorenje-naturefresh','description'=>'Холодильник с зоной свежести и низким энергопотреблением','price'=>'640.00'],
            ['id'=>13,'name'=>'Midea SmartCool','slug'=>'midea-smartcool','description'=>'Холодильник с поддержкой мобильного приложения и умного дома','price'=>'810.00'],
            ['id'=>14,'name'=>'Sharp Plasmacluster','slug'=>'sharp-plasmacluster','description'=>'Холодильник с технологией очистки воздуха Plasmacluster','price'=>'870.00'],
            ['id'=>15,'name'=>'Siemens HyperFresh','slug'=>'siemens-hyperfresh','description'=>'Холодильник с системой HyperFresh и высоким классом энергоэффективности','price'=>'990.00'],

            ['id'=>16,'name'=>'LG TurboWash','slug'=>'lg-turbowash','description'=>'Стиральная машина LG с технологией TurboWash и высокой скоростью отжима','price'=>'520.00'],
            ['id'=>17,'name'=>'Samsung EcoBubble','slug'=>'samsung-ecobubble','description'=>'Стиральная машина Samsung с технологией EcoBubble и бережной стиркой','price'=>'560.00'],
            ['id'=>18,'name'=>'Bosch Serie 6','slug'=>'bosch-serie-6-washer','description'=>'Энергоэффективная стиральная машина Bosch с множеством программ','price'=>'600.00'],
            ['id'=>19,'name'=>'Whirlpool FreshCare+','slug'=>'whirlpool-freshcare','description'=>'Стиральная машина Whirlpool с функцией FreshCare+ и инверторным двигателем','price'=>'480.00'],
            ['id'=>20,'name'=>'Electrolux PerfectCare','slug'=>'electrolux-perfectcare','description'=>'Стиральная машина Electrolux PerfectCare с системой бережной стирки','price'=>'590.00'],

            ['id'=>21,'name'=>'Samsung Galaxy S23','slug'=>'samsung-galaxy-s23','description'=>'Флагманский смартфон Samsung с мощным процессором и камерой','price'=>'799.00'],
            ['id'=>22,'name'=>'Samsung Galaxy S23 Ultra','slug'=>'samsung-galaxy-s23-ultra','description'=>'Смартфон Samsung с экраном 6.8" и камерой 200 Мп','price'=>'1199.00'],
            ['id'=>23,'name'=>'Samsung Galaxy Z Flip5','slug'=>'samsung-galaxy-z-flip5','description'=>'Складной смартфон Samsung с гибким дисплеем','price'=>'999.00'],
            ['id'=>24,'name'=>'Samsung Galaxy Z Fold5','slug'=>'samsung-galaxy-z-fold5','description'=>'Смартфон Samsung с большим складным экраном для работы и развлечений','price'=>'1499.00'],
            ['id'=>25,'name'=>'Samsung Galaxy A54','slug'=>'samsung-galaxy-a54','description'=>'Доступный смартфон Samsung с хорошей камерой и батареей','price'=>'399.00'],

            ['id'=>26,'name'=>'Lenovo ThinkPad X1 Carbon','slug'=>'lenovo-thinkpad-x1-carbon','description'=>'Ультрабук Lenovo ThinkPad X1 Carbon с лёгким корпусом и высокой производительностью','price'=>'1450.00'],
            ['id'=>27,'name'=>'Lenovo Yoga Slim 7','slug'=>'lenovo-yoga-slim-7','description'=>'Тонкий и лёгкий ноутбук Lenovo Yoga Slim 7 с экраном 14"','price'=>'980.00'],
            ['id'=>28,'name'=>'Lenovo Legion 5 Pro','slug'=>'lenovo-legion-5-pro','description'=>'Игровой ноутбук Lenovo Legion 5 Pro с экраном 16" и мощной графикой','price'=>'1650.00'],
            ['id'=>29,'name'=>'Lenovo IdeaPad 3','slug'=>'lenovo-ideapad-3','description'=>'Бюджетный ноутбук Lenovo IdeaPad 3 для повседневных задач','price'=>'550.00'],
            ['id'=>30,'name'=>'Lenovo ThinkBook 14s Yoga','slug'=>'lenovo-thinkbook-14s-yoga','description'=>'Универсальный ноутбук Lenovo ThinkBook 14s Yoga с сенсорным экраном','price'=>'1100.00'],

            ['id'=>31,'name'=>'Asus ROG Strix RTX 4090','slug'=>'asus-rog-strix-rtx4090','description'=>'Флагманская видеокарта Asus ROG Strix RTX 4090 с максимальной производительностью','price'=>'2999.00'],
            ['id'=>32,'name'=>'Asus TUF Gaming RTX 4080','slug'=>'asus-tuf-rtx4080','description'=>'Игровая видеокарта Asus TUF Gaming RTX 4080 с усиленным охлаждением','price'=>'1899.00'],
            ['id'=>33,'name'=>'Asus Dual RTX 4070 Ti','slug'=>'asus-dual-rtx4070ti','description'=>'Видеокарта Asus Dual RTX 4070 Ti с двойным охлаждением','price'=>'1099.00'],
            ['id'=>34,'name'=>'Asus ROG Strix RX 7900 XTX','slug'=>'asus-rog-strix-rx7900xtx','description'=>'Флагманская видеокарта Asus ROG Strix RX 7900 XTX на базе AMD','price'=>'1399.00'],
            ['id'=>35,'name'=>'Asus TUF Gaming RX 7800 XT','slug'=>'asus-tuf-rx7800xt','description'=>'Игровая видеокарта Asus TUF Gaming RX 7800 XT с надёжным охлаждением','price'=>'799.00'],

            ['id'=>36,'name'=>'MSI GeForce RTX 4090 Suprim X','slug'=>'msi-rtx4090-suprimx','description'=>'Флагманская видеокарта MSI RTX 4090 Suprim X с тройным охлаждением','price'=>'2999.00'],
            ['id'=>37,'name'=>'MSI Gaming X Trio RTX 4080','slug'=>'msi-rtx4080-gamingxtrio','description'=>'Игровая видеокарта MSI RTX 4080 Gaming X Trio с тройным охлаждением','price'=>'1899.00'],
            ['id'=>38,'name'=>'MSI Ventus 3X RTX 4070 Ti','slug'=>'msi-rtx4070ti-ventus3x','description'=>'Видеокарта MSI Ventus 3X RTX 4070 Ti с тройным охлаждением','price'=>'1099.00'],
            ['id'=>39,'name'=>'MSI Radeon RX 7900 XTX Gaming Trio','slug'=>'msi-rx7900xtx-gamingtrio','description'=>'Флагманская видеокарта MSI RX 7900 XTX Gaming Trio на базе AMD','price'=>'1399.00'],
            ['id'=>40,'name'=>'MSI Mech 2X RX 7800 XT','slug'=>'msi-rx7800xt-mech2x','description'=>'Видеокарта MSI Mech 2X RX 7800 XT с двойным охлаждением','price'=>'799.00'],

            ['id'=>41,'name'=>'Intel Core i9-14900K','slug'=>'intel-core-i9-14900k','description'=>'Флагманский процессор Intel Core i9-14900K для энтузиастов','price'=>'699.00'],
            ['id'=>42,'name'=>'Intel Core i7-14700K','slug'=>'intel-core-i7-14700k','description'=>'Процессор Intel Core i7-14700K с высокой производительностью','price'=>'499.00'],
            ['id'=>43,'name'=>'Intel Core i5-14600K','slug'=>'intel-core-i5-14600k','description'=>'Процессор Intel Core i5-14600K для геймеров и создателей контента','price'=>'349.00'],
            ['id'=>44,'name'=>'AMD Ryzen 9 7950X','slug'=>'amd-ryzen-9-7950x','description'=>'Флагманский процессор AMD Ryzen 9 7950X на архитектуре Zen 4','price'=>'699.00'],
            ['id'=>45,'name'=>'AMD Ryzen 7 7800X3D','slug'=>'amd-ryzen-7-7800x3d','description'=>'Игровой процессор AMD Ryzen 7 7800X3D с технологией 3D V-Cache','price'=>'449.00'],
            ['id'=>46,'name'=>'AMD Ryzen 5 7600X','slug'=>'amd-ryzen-5-7600x','description'=>'Процессор AMD Ryzen 5 7600X на архитектуре Zen 4','price'=>'299.00'],
            ['id'=>47,'name'=>'AMD Ryzen 3 5300G','slug'=>'amd-ryzen-3-5300g','description'=>'Бюджетный процессор AMD Ryzen 3 5300G с встроенной графикой','price'=>'149.00'],
            ['id'=>48,'name'=>'Intel Core i3-14100','slug'=>'intel-core-i3-14100','description'=>'Процессор Intel Core i3-14100 для офисных и домашних задач','price'=>'129.00'],
            ['id'=>49,'name'=>'Intel Xeon W-3495X','slug'=>'intel-xeon-w-3495x','description'=>'Профессиональный процессор Intel Xeon W-3495X для рабочих станций','price'=>'5199.00'],
            ['id'=>50,'name'=>'AMD EPYC 9654','slug'=>'amd-epyc-9654','description'=>'Серверный процессор AMD EPYC 9654 на архитектуре Zen 4c','price'=>'6999.00']

        ])->into('products')->exec();

        // attributes
        DB::insert([
            ['id'=>1,'name'=>'Аудио выход','slug'=>'ports_audio_out','description'=>'Аудио выход','type'=>'boolean'],
            ['id'=>2,'name'=>'Бренд','slug'=>'brand','description'=>'Производитель устройства','type'=>'string'],
            ['id'=>3,'name'=>'Bluetooth','slug'=>'bluetooth','description'=>'Поддержка Bluetooth','type'=>'boolean'],
            ['id'=>4,'name'=>'Вес','slug'=>'weight','description'=>'Вес устройства','type'=>'number'],
            ['id'=>5,'name'=>'Веб камера','slug'=>'webcam','description'=>'Наличие веб камеры','type'=>'boolean'],
            ['id'=>6,'name'=>'Высота','slug'=>'height','description'=>'Высота устройства','type'=>'number'],
            ['id'=>7,'name'=>'Гарантия','slug'=>'warranty_months','description'=>'Гарантия в месяцах','type'=>'number'],
            ['id'=>8,'name'=>'Глубина','slug'=>'depth','description'=>'Глубина устройства','type'=>'number'],
            ['id'=>9,'name'=>'Год выпуска','slug'=>'release_year','description'=>'Год выхода модели','type'=>'number'],
            ['id'=>10,'name'=>'Дата анонса','slug'=>'announcement_date','description'=>'Дата анонса устройства','type'=>'string'],
            ['id'=>11,'name'=>'Дата начала продаж','slug'=>'sales_start_date','description'=>'Дата начала продаж','type'=>'string'],
            ['id'=>12,'name'=>'Диагональ экрана','slug'=>'screen_size','description'=>'Диагональ экрана','type'=>'number'],
            ['id'=>13,'name'=>'Емкость аккумулятора','slug'=>'battery_capacity','description'=>'Емкость батареи','type'=>'number'],
            ['id'=>14,'name'=>'Емкость холодильника','slug'=>'fridge_capacity','description'=>'Общий объем холодильника','type'=>'number'],
            ['id'=>15,'name'=>'Загрузка белья','slug'=>'washer_load','description'=>'Максимальная загрузка','type'=>'number'],
            ['id'=>16,'name'=>'Зона свежести','slug'=>'fresh_zone','description'=>'Наличие зоны свежести','type'=>'boolean'],
            ['id'=>17,'name'=>'Инверторный двигатель','slug'=>'inverter_motor','description'=>'Инверторный двигатель','type'=>'boolean'],
            ['id'=>18,'name'=>'Кэш L1','slug'=>'cpu_cache_l1','description'=>'Кэш L1','type'=>'number'],
            ['id'=>19,'name'=>'Кэш L2','slug'=>'cpu_cache_l2','description'=>'Кэш L2','type'=>'number'],
            ['id'=>20,'name'=>'Кэш L3','slug'=>'cpu_cache_l3','description'=>'Кэш L3','type'=>'number'],
            ['id'=>21,'name'=>'Класс энергоэффективности','slug'=>'energy_class','description'=>'Класс энергоэффективности','type'=>'string'],
            ['id'=>22,'name'=>'Класс HEPA фильтра','slug'=>'hepa_class','description'=>'Класс HEPA фильтра','type'=>'string'],
            ['id'=>23,'name'=>'Количество вентиляторов','slug'=>'fans_count','description'=>'Количество вентиляторов','type'=>'number'],
            ['id'=>24,'name'=>'Количество вентиляторов GPU','slug'=>'gpu_fans','description'=>'Количество вентиляторов','type'=>'number'],
            ['id'=>25,'name'=>'Количество динамиков','slug'=>'speaker_count','description'=>'Количество динамиков','type'=>'number'],
            ['id'=>26,'name'=>'Количество камер','slug'=>'fridge_chambers','description'=>'Количество камер','type'=>'number'],
            ['id'=>27,'name'=>'Количество M2 слотов','slug'=>'m2_slots','description'=>'Количество M.2 слотов','type'=>'number'],
            ['id'=>28,'name'=>'Количество модулей RAM','slug'=>'ram_modules','description'=>'Количество модулей','type'=>'number'],
            ['id'=>29,'name'=>'Количество PCIe слотов','slug'=>'pcie_slots','description'=>'Количество PCI Express слотов','type'=>'number'],
            ['id'=>30,'name'=>'Количество программ','slug'=>'wash_programs','description'=>'Количество программ стирки','type'=>'number'],
            ['id'=>31,'name'=>'Количество потоков CPU','slug'=>'cpu_threads','description'=>'Количество потоков','type'=>'number'],
            ['id'=>32,'name'=>'Количество слотов RAM','slug'=>'ram_slots','description'=>'Количество слотов оперативной памяти','type'=>'number'],
            ['id'=>33,'name'=>'Количество ядер CPU','slug'=>'cpu_cores','description'=>'Количество ядер','type'=>'number'],
            ['id'=>34,'name'=>'Количество SATA портов','slug'=>'sata_ports','description'=>'Количество SATA портов','type'=>'number'],
            ['id'=>35,'name'=>'Количество USB','slug'=>'ports_usb','description'=>'Количество USB','type'=>'number'],
            ['id'=>36,'name'=>'Количество USB-C','slug'=>'ports_usb_c','description'=>'Количество USB-C','type'=>'number'],
            ['id'=>37,'name'=>'Количество HDMI','slug'=>'ports_hdmi','description'=>'Количество HDMI','type'=>'number'],
            ['id'=>38,'name'=>'Количество DisplayPort','slug'=>'ports_displayport','description'=>'Количество DisplayPort','type'=>'number'],
            ['id'=>39,'name'=>'Контрастность','slug'=>'screen_contrast','description'=>'Контрастность','type'=>'number'],
            ['id'=>40,'name'=>'Крепление VESA','slug'=>'vesa_mount','description'=>'Поддержка VESA','type'=>'boolean'],
            ['id'=>41,'name'=>'Материал корпуса','slug'=>'case_material','description'=>'Материал корпуса','type'=>'string'],
            ['id'=>42,'name'=>'Мобильное приложение','slug'=>'mobile_app','description'=>'Поддержка мобильного приложения','type'=>'boolean'],
            ['id'=>43,'name'=>'Модель','slug'=>'model','description'=>'Модель устройства','type'=>'string'],
            ['id'=>44,'name'=>'Модель GPU','slug'=>'gpu_model','description'=>'Модель видеокарты','type'=>'string'],
            ['id'=>45,'name'=>'Модель процессора','slug'=>'cpu_model','description'=>'Модель процессора','type'=>'string'],
            ['id'=>46,'name'=>'Мощность блока питания','slug'=>'psu_power','description'=>'Мощность БП','type'=>'number'],
            ['id'=>47,'name'=>'Мощность всасывания','slug'=>'suction_power','description'=>'Мощность всасывания','type'=>'number'],
            ['id'=>48,'name'=>'Мощность зарядного устройства','slug'=>'charger_power','description'=>'Мощность зарядки','type'=>'number'],
            ['id'=>49,'name'=>'Мощность микроволновки','slug'=>'microwave_power','description'=>'Мощность микроволновки','type'=>'number'],
            ['id'=>50,'name'=>'Назначение','slug'=>'purpose','description'=>'Назначение устройства','type'=>'string'],
            ['id'=>51,'name'=>'Объем видеопамяти','slug'=>'gpu_memory','description'=>'Объем VRAM','type'=>'number'],
            ['id'=>52,'name'=>'Объем микроволновки','slug'=>'microwave_volume','description'=>'Объем камеры','type'=>'number'],
            ['id'=>53,'name'=>'Объем морозильной камеры','slug'=>'freezer_capacity','description'=>'Объем морозилки','type'=>'number'],
            ['id'=>54,'name'=>'Объем накопителя','slug'=>'storage_capacity','description'=>'Объем накопителя','type'=>'number'],
            ['id'=>55,'name'=>'Объем пылесборника','slug'=>'dust_collector_volume','description'=>'Объем пылесборника','type'=>'number'],
            ['id'=>56,'name'=>'Объем RAM','slug'=>'ram_size','description'=>'Объем RAM','type'=>'number'],
            ['id'=>57,'name'=>'Описание атрибута','slug'=>'description','description'=>'Описание атрибута','type'=>'string'],
            ['id'=>58,'name'=>'Описание значения атрибута','slug'=>'description','description'=>'Описание значения атрибута','type'=>'string'],
            ['id'=>59,'name'=>'Поддержка Bluetooth','slug'=>'bluetooth','description'=>'Поддержка Bluetooth','type'=>'boolean'],
            ['id'=>60,'name'=>'Поддержка HDR','slug'=>'hdr_support','description'=>'Поддержка HDR','type'=>'boolean'],
            ['id'=>61,'name'=>'Поддержка HDR форматов','slug'=>'hdr_formats','description'=>'Поддерживаемые HDR форматы','type'=>'string'],
            ['id'=>62,'name'=>'Поддержка нескольких мониторов','slug'=>'multi_monitor_support','description'=>'Поддержка нескольких мониторов','type'=>'boolean'],
            ['id'=>63,'name'=>'Поддержка NVMe','slug'=>'nvme_support','description'=>'Поддержка NVMe накопителей','type'=>'boolean'],
            ['id'=>64,'name'=>'Поддержка Ray Tracing','slug'=>'gpu_ray_tracing','description'=>'Поддержка трассировки лучей','type'=>'boolean'],
            ['id'=>65,'name'=>'Поддержка умного дома','slug'=>'smart_home_support','description'=>'Интеграция с умным домом','type'=>'boolean'],
            ['id'=>66,'name'=>'Подсветка клавиатуры','slug'=>'keyboard_backlight','description'=>'Наличие подсветки клавиатуры','type'=>'boolean'],
            ['id'=>67,'name'=>'Поворот экрана','slug'=>'screen_rotation','description'=>'Возможность поворота','type'=>'boolean'],
            ['id'=>68,'name'=>'Потребление энергии','slug'=>'energy_consumption','description'=>'Потребление энергии','type'=>'number'],
            ['id'=>69,'name'=>'Разрешение веб камеры','slug'=>'webcam_resolution','description'=>'Разрешение камеры','type'=>'string'],
            ['id'=>70,'name'=>'Разрешение экрана','slug'=>'screen_resolution','description'=>'Разрешение экрана','type'=>'string'],
            ['id'=>71,'name'=>'Регулировка высоты','slug'=>'height_adjustment','description'=>'Регулировка высоты подставки','type'=>'boolean'],
            ['id'=>72,'name'=>'Серия','slug'=>'series','description'=>'Линейка устройства','type'=>'string'],
            ['id'=>73,'name'=>'Сертификат БП','slug'=>'psu_certificate','description'=>'Сертификат эффективности','type'=>'string'],
            ['id'=>74,'name'=>'Скорость записи','slug'=>'storage_write_speed','description'=>'Скорость записи','type'=>'number'],
            ['id'=>75,'name'=>'Скорость отжима','slug'=>'spin_speed','description'=>'Максимальная скорость отжима','type'=>'number'],
            ['id'=>76,'name'=>'Скорость чтения','slug'=>'storage_read_speed','description'=>'Скорость чтения','type'=>'number'],
            ['id'=>77,'name'=>'Сокет CPU','slug'=>'cpu_socket','description'=>'Сокет процессора','type'=>'string'],
            ['id'=>78,'name'=>'Статус атрибута','slug'=>'status','description'=>'Статус атрибута','type'=>'string'],
            ['id'=>79,'name'=>'Статус значения атрибута','slug'=>'status','description'=>'Статус значения атрибута','type'=>'string'],
            ['id'=>80,'name'=>'Страна производства','slug'=>'country_of_origin','description'=>'Страна производства','type'=>'string'],
            ['id'=>81,'name'=>'Техпроцесс CPU','slug'=>'cpu_process_nm','description'=>'Техпроцесс','type'=>'number'],
            ['id'=>82,'name'=>'Тип аккумулятора','slug'=>'battery_type','description'=>'Тип батареи','type'=>'string'],
            ['id'=>83,'name'=>'Тип видеокарты','slug'=>'gpu_type','description'=>'Тип видеокарты','type'=>'string'],
            ['id'=>84,'name'=>'Тип видеопамяти','slug'=>'gpu_memory_type','description'=>'Тип памяти','type'=>'string'],
            ['id'=>85,'name'=>'Тип дисплея','slug'=>'display_type','description'=>'Тип встроенного дисплея','type'=>'string'],
            ['id'=>86,'name'=>'Тип корпуса ПК','slug'=>'pc_case_type','description'=>'Тип корпуса компьютера','type'=>'string'],
            ['id'=>87,'name'=>'Тип клавиатуры ноутбука','slug'=>'laptop_keyboard_type','description'=>'Тип клавиатуры','type'=>'string'],
            ['id'=>88,'name'=>'Тип матрицы','slug'=>'screen_panel_type','description'=>'Тип матрицы','type'=>'string'],
            ['id'=>89,'name'=>'Тип накопителя','slug'=>'storage_type','description'=>'Тип накопителя','type'=>'string'],
            ['id'=>90,'name'=>'Тип панели управления','slug'=>'control_panel_type','description'=>'Тип панели управления','type'=>'string'],
            ['id'=>91,'name'=>'Тип пылесборника','slug'=>'dust_collector_type','description'=>'Тип пылесборника','type'=>'string'],
            ['id'=>92,'name'=>'Тип пылесоса','slug'=>'vacuum_type','description'=>'Тип пылесоса','type'=>'string'],
            ['id'=>93,'name'=>'Тип процессора','slug'=>'cpu_type','description'=>'Тип процессора','type'=>'string'],
            ['id'=>94,'name'=>'Тип стиральной машины','slug'=>'washer_type','description'=>'Тип стиральной машины','type'=>'string'],
            ['id'=>95,'name'=>'Тип управления','slug'=>'control_type','description'=>'Тип управления','type'=>'string'],
            ['id'=>96,'name'=>'Тип фильтра','slug'=>'filter_type','description'=>'Тип фильтра','type'=>'string'],
            ['id'=>97,'name'=>'Тип форм-фактора накопителя','slug'=>'storage_form_factor','description'=>'Форм-фактор','type'=>'string'],
            ['id'=>98,'name'=>'Тип охлаждения','slug'=>'cooling_type','description'=>'Тип охлаждения','type'=>'string'],
            ['id'=>99,'name'=>'Тип чипсета материнской платы','slug'=>'motherboard_chipset','description'=>'Чипсет материнской платы','type'=>'string'],
            ['id'=>100,'name'=>'Тип контейнера пылесоса','slug'=>'vacuum_container_type','description'=>'Тип контейнера','type'=>'string'],
            ['id'=>101,'name'=>'Турбо частота CPU','slug'=>'cpu_turbo_frequency','description'=>'Turbo частота','type'=>'number'],
            ['id'=>102,'name'=>'Удаленное управление','slug'=>'remote_control','description'=>'Удаленное управление','type'=>'boolean'],
            ['id'=>103,'name'=>'Угол обзора','slug'=>'viewing_angle','description'=>'Угол обзора','type'=>'number'],
            ['id'=>104,'name'=>'Уровень вибрации','slug'=>'vibration_level','description'=>'Уровень вибрации','type'=>'number'],
            ['id'=>105,'name'=>'Уровень шума','slug'=>'noise_level','description'=>'Уровень шума','type'=>'number'],
            ['id'=>106,'name'=>'Форм-фактор материнской платы','slug'=>'motherboard_form_factor','description'=>'Форм-фактор платы','type'=>'string'],
            ['id'=>107,'name'=>'Характеристики CPU: частота','slug'=>'cpu_frequency','description'=>'Базовая частота процессора','type'=>'number'],
            ['id'=>108,'name'=>'Частота GPU','slug'=>'gpu_frequency','description'=>'Частота GPU','type'=>'number'],
            ['id'=>109,'name'=>'Частота памяти GPU','slug'=>'gpu_memory_frequency','description'=>'Частота памяти','type'=>'number'],
            ['id'=>110,'name'=>'Частота RAM','slug'=>'ram_frequency','description'=>'Частота RAM','type'=>'number'],
            ['id'=>111,'name'=>'Частота обновления','slug'=>'screen_refresh_rate','description'=>'Частота обновления','type'=>'number'],
            ['id'=>112,'name'=>'Цвет','slug'=>'color','description'=>'Цвет корпуса','type'=>'string'],
            ['id'=>113,'name'=>'Целевая аудитория','slug'=>'target_audience','description'=>'Для кого предназначено устройство','type'=>'string'],
            ['id'=>114,'name'=>'Чипсет материнской платы','slug'=>'motherboard_chipset','description'=>'Чипсет материнской платы','type'=>'string'],
            ['id'=>115,'name'=>'Шина памяти GPU','slug'=>'gpu_memory_bus','description'=>'Ширина шины','type'=>'number'],
            ['id'=>116,'name'=>'Ширина','slug'=>'width','description'=>'Ширина устройства','type'=>'number'],
            ['id'=>117,'name'=>'Энергопотребление','slug'=>'energy_consumption','description'=>'Потребление энергии','type'=>'number'],
            ['id'=>118,'name'=>'Ethernet порт','slug'=>'ports_ethernet','description'=>'Наличие Ethernet','type'=>'boolean'],
            ['id'=>119,'name'=>'Язык клавиатуры','slug'=>'keyboard_language','description'=>'Язык раскладки','type'=>'string'],
            ['id'=>120,'name'=>'Яркость','slug'=>'screen_brightness','description'=>'Яркость','type'=>'number']
        ])->into('attributes')->exec();

        // product_category
        DB::insert([
            ['product_id'=>1,'category_id'=>26],
            ['product_id'=>2,'category_id'=>26],
            ['product_id'=>3,'category_id'=>26],
            ['product_id'=>4,'category_id'=>26],
            ['product_id'=>5,'category_id'=>26],
            ['product_id'=>6,'category_id'=>26],
            ['product_id'=>7,'category_id'=>26],
            ['product_id'=>8,'category_id'=>26],
            ['product_id'=>9,'category_id'=>26],
            ['product_id'=>10,'category_id'=>26],
            ['product_id'=>11,'category_id'=>26],
            ['product_id'=>12,'category_id'=>26],
            ['product_id'=>13,'category_id'=>26],
            ['product_id'=>14,'category_id'=>26],
            ['product_id'=>15,'category_id'=>26],

            ['product_id'=>16,'category_id'=>27],
            ['product_id'=>17,'category_id'=>27],
            ['product_id'=>18,'category_id'=>27],
            ['product_id'=>19,'category_id'=>27],
            ['product_id'=>20,'category_id'=>27],

            ['product_id'=>21,'category_id'=>15],
            ['product_id'=>22,'category_id'=>15],
            ['product_id'=>23,'category_id'=>15],
            ['product_id'=>24,'category_id'=>15],
            ['product_id'=>25,'category_id'=>15],

            ['product_id'=>26,'category_id'=>68],
            ['product_id'=>27,'category_id'=>68],
            ['product_id'=>28,'category_id'=>68],
            ['product_id'=>29,'category_id'=>68],
            ['product_id'=>30,'category_id'=>68],

            ['product_id'=>31,'category_id'=>59],
            ['product_id'=>32,'category_id'=>59],
            ['product_id'=>33,'category_id'=>59],
            ['product_id'=>34,'category_id'=>59],
            ['product_id'=>35,'category_id'=>59],

            ['product_id'=>36,'category_id'=>60],
            ['product_id'=>37,'category_id'=>60],
            ['product_id'=>38,'category_id'=>60],
            ['product_id'=>39,'category_id'=>60],
            ['product_id'=>40,'category_id'=>60],
                        
            ['product_id'=>41,'category_id'=>24],
            ['product_id'=>42,'category_id'=>24],
            ['product_id'=>43,'category_id'=>24],
            ['product_id'=>44,'category_id'=>24],
            ['product_id'=>45,'category_id'=>24],
            ['product_id'=>46,'category_id'=>24],
            ['product_id'=>47,'category_id'=>24],
            ['product_id'=>48,'category_id'=>24],
            ['product_id'=>49,'category_id'=>24],
            ['product_id'=>50,'category_id'=>24]

        ])->into('product_category')->exec();
     
        // product_attributes
        DB::insert([
            // LG InstaView
            ['product_id'=>1,'attribute_id'=>14,'description'=>'Общий объём','value'=>'450'],
            ['product_id'=>1,'attribute_id'=>53,'description'=>'Морозильная камера','value'=>'120'],
            ['product_id'=>1,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Корея'],
            ['product_id'=>1,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A++'],
            ['product_id'=>1,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],

            // Samsung Family Hub
            ['product_id'=>2,'attribute_id'=>14,'description'=>'Общий объём','value'=>'500'],
            ['product_id'=>2,'attribute_id'=>53,'description'=>'Морозильная камера','value'=>'150'],
            ['product_id'=>2,'attribute_id'=>65,'description'=>'Умный дом','value'=>'Да'],
            ['product_id'=>2,'attribute_id'=>42,'description'=>'Мобильное приложение','value'=>'Да'],
            ['product_id'=>2,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A+'],

            // Bosch Serie 6
            ['product_id'=>3,'attribute_id'=>14,'description'=>'Общий объём','value'=>'400'],
            ['product_id'=>3,'attribute_id'=>53,'description'=>'Морозильная камера','value'=>'100'],
            ['product_id'=>3,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'NoFrost'],
            ['product_id'=>3,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A++'],
            ['product_id'=>3,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'38'],

            // Whirlpool FreshZone
            ['product_id'=>4,'attribute_id'=>14,'description'=>'Общий объём','value'=>'420'],
            ['product_id'=>4,'attribute_id'=>53,'description'=>'Морозильная камера','value'=>'110'],
            ['product_id'=>4,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],
            ['product_id'=>4,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'36'],
            ['product_id'=>4,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A+'],

            // Electrolux TwinTech
            ['product_id'=>5,'attribute_id'=>14,'description'=>'Общий объём','value'=>'460'],
            ['product_id'=>5,'attribute_id'=>53,'description'=>'Морозильная камера','value'=>'130'],
            ['product_id'=>5,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'TwinTech'],
            ['product_id'=>5,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A++'],
            ['product_id'=>5,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'250'],
            // LG DoorCooling+
            ['product_id'=>6,'attribute_id'=>14,'description'=>'Общий объём','value'=>'430'],
            ['product_id'=>6,'attribute_id'=>53,'description'=>'Объем морозильной камеры','value'=>'110'],
            ['product_id'=>6,'attribute_id'=>26,'description'=>'Количество камер','value'=>'2'],
            ['product_id'=>6,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],
            ['product_id'=>6,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'DoorCooling+'],
            ['product_id'=>6,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'240'],
            ['product_id'=>6,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A++'],
            ['product_id'=>6,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Корея'],
            ['product_id'=>6,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'37'],
            ['product_id'=>6,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>6,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Низкий'],
            ['product_id'=>6,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>6,'attribute_id'=>6,'description'=>'Высота','value'=>'180'],
            ['product_id'=>6,'attribute_id'=>116,'description'=>'Ширина','value'=>'70'],
            ['product_id'=>6,'attribute_id'=>8,'description'=>'Глубина','value'=>'68'],
            ['product_id'=>6,'attribute_id'=>4,'description'=>'Вес','value'=>'75'],

            // Samsung Bespoke
            ['product_id'=>7,'attribute_id'=>14,'description'=>'Общий объём','value'=>'490'],
            ['product_id'=>7,'attribute_id'=>53,'description'=>'Объем морозильной камеры','value'=>'140'],
            ['product_id'=>7,'attribute_id'=>26,'description'=>'Количество камер','value'=>'3'],
            ['product_id'=>7,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],
            ['product_id'=>7,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'Bespoke Cooling'],
            ['product_id'=>7,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'260'],
            ['product_id'=>7,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A+'],
            ['product_id'=>7,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Корея'],
            ['product_id'=>7,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'38'],
            ['product_id'=>7,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>7,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Средний'],
            ['product_id'=>7,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл и стекло'],
            ['product_id'=>7,'attribute_id'=>6,'description'=>'Высота','value'=>'185'],
            ['product_id'=>7,'attribute_id'=>116,'description'=>'Ширина','value'=>'72'],
            ['product_id'=>7,'attribute_id'=>8,'description'=>'Глубина','value'=>'70'],
            ['product_id'=>7,'attribute_id'=>4,'description'=>'Вес','value'=>'80'],

            // Bosch VitaFresh
            ['product_id'=>8,'attribute_id'=>14,'description'=>'Общий объём','value'=>'410'],
            ['product_id'=>8,'attribute_id'=>53,'description'=>'Объем морозильной камеры','value'=>'100'],
            ['product_id'=>8,'attribute_id'=>26,'description'=>'Количество камер','value'=>'2'],
            ['product_id'=>8,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],
            ['product_id'=>8,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'VitaFresh'],
            ['product_id'=>8,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'230'],
            ['product_id'=>8,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A++'],
            ['product_id'=>8,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Германия'],
            ['product_id'=>8,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'39'],
            ['product_id'=>8,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>8,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Низкий'],
            ['product_id'=>8,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>8,'attribute_id'=>6,'description'=>'Высота','value'=>'185'],
            ['product_id'=>8,'attribute_id'=>116,'description'=>'Ширина','value'=>'70'],
            ['product_id'=>8,'attribute_id'=>8,'description'=>'Глубина','value'=>'68'],
            ['product_id'=>8,'attribute_id'=>4,'description'=>'Вес','value'=>'78'],

            // Whirlpool NoFrost
            ['product_id'=>9,'attribute_id'=>14,'description'=>'Общий объём','value'=>'420'],
            ['product_id'=>9,'attribute_id'=>53,'description'=>'Объем морозильной камеры','value'=>'115'],
            ['product_id'=>9,'attribute_id'=>26,'description'=>'Количество камер','value'=>'2'],
            ['product_id'=>9,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],
            ['product_id'=>9,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'NoFrost'],
            ['product_id'=>9,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'240'],
            ['product_id'=>9,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A+'],
            ['product_id'=>9,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Италия'],
            ['product_id'=>9,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'36'],
            ['product_id'=>9,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>9,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Средний'],
            ['product_id'=>9,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>9,'attribute_id'=>6,'description'=>'Высота','value'=>'182'],
            ['product_id'=>9,'attribute_id'=>116,'description'=>'Ширина','value'=>'71'],
            ['product_id'=>9,'attribute_id'=>8,'description'=>'Глубина','value'=>'69'],
            ['product_id'=>9,'attribute_id'=>4,'description'=>'Вес','value'=>'76'],

            // Electrolux Cooling 360
            ['product_id'=>10,'attribute_id'=>14,'description'=>'Общий объём','value'=>'460'],
            ['product_id'=>10,'attribute_id'=>53,'description'=>'Объем морозильной камеры','value'=>'130'],
            ['product_id'=>10,'attribute_id'=>26,'description'=>'Количество камер','value'=>'2'],
            ['product_id'=>10,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],
            ['product_id'=>10,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'Cooling 360'],
            ['product_id'=>10,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'250'],
            ['product_id'=>10,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A++'],
            ['product_id'=>10,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Швеция'],
            ['product_id'=>10,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'37'],
            ['product_id'=>10,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>10,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Низкий'],
            ['product_id'=>10,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>10,'attribute_id'=>6,'description'=>'Высота','value'=>'186'],
            ['product_id'=>10,'attribute_id'=>116,'description'=>'Ширина','value'=>'72'],
            ['product_id'=>10,'attribute_id'=>8,'description'=>'Глубина','value'=>'70'],
            ['product_id'=>10,'attribute_id'=>4,'description'=>'Вес','value'=>'79'],

            // Haier MultiAirFlow
            ['product_id'=>11,'attribute_id'=>14,'description'=>'Общий объём','value'=>'470'],
            ['product_id'=>11,'attribute_id'=>53,'description'=>'Объем морозильной камеры','value'=>'125'],
            ['product_id'=>11,'attribute_id'=>26,'description'=>'Количество камер','value'=>'3'],
            ['product_id'=>11,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],
            ['product_id'=>11,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'MultiAirFlow'],
            ['product_id'=>11,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'255'],
            ['product_id'=>11,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A+'],
            ['product_id'=>11,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Китай'],
            ['product_id'=>11,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'38'],
            ['product_id'=>11,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>11,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Средний'],
            ['product_id'=>11,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>11,'attribute_id'=>6,'description'=>'Высота','value'=>'183'],
            ['product_id'=>11,'attribute_id'=>116,'description'=>'Ширина','value'=>'70'],
            ['product_id'=>11,'attribute_id'=>8,'description'=>'Глубина','value'=>'68'],
            ['product_id'=>11,'attribute_id'=>4,'description'=>'Вес','value'=>'77'],

            // Gorenje NatureFresh
            ['product_id'=>12,'attribute_id'=>14,'description'=>'Общий объём','value'=>'400'],
            ['product_id'=>12,'attribute_id'=>53,'description'=>'Объем морозильной камеры','value'=>'100'],
            ['product_id'=>12,'attribute_id'=>26,'description'=>'Количество камер','value'=>'2'],
            ['product_id'=>12,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],
            ['product_id'=>12,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'NatureFresh'],
            ['product_id'=>12,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'220'],
            ['product_id'=>12,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A++'],
            ['product_id'=>12,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Словения'],
            ['product_id'=>12,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'37'],
            ['product_id'=>12,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>12,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Низкий'],
            ['product_id'=>12,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>12,'attribute_id'=>6,'description'=>'Высота','value'=>'184'],
            ['product_id'=>12,'attribute_id'=>116,'description'=>'Ширина','value'=>'70'],
            ['product_id'=>12,'attribute_id'=>8,'description'=>'Глубина','value'=>'68'],
            ['product_id'=>12,'attribute_id'=>4,'description'=>'Вес','value'=>'74'],

            // Midea SmartCool
            ['product_id'=>13,'attribute_id'=>14,'description'=>'Общий объём','value'=>'450'],
            ['product_id'=>13,'attribute_id'=>53,'description'=>'Объем морозильной камеры','value'=>'120'],
            ['product_id'=>13,'attribute_id'=>26,'description'=>'Количество камер','value'=>'2'],
            ['product_id'=>13,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],
            ['product_id'=>13,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'SmartCool'],
            ['product_id'=>13,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'240'],
            ['product_id'=>13,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A+'],
            ['product_id'=>13,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Китай'],
            ['product_id'=>13,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'38'],
            ['product_id'=>13,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>13,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Средний'],
            ['product_id'=>13,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>13,'attribute_id'=>6,'description'=>'Высота','value'=>'185'],
            ['product_id'=>13,'attribute_id'=>116,'description'=>'Ширина','value'=>'71'],
            ['product_id'=>13,'attribute_id'=>8,'description'=>'Глубина','value'=>'69'],
            ['product_id'=>13,'attribute_id'=>4,'description'=>'Вес','value'=>'76'],

            // Sharp Plasmacluster
            ['product_id'=>14,'attribute_id'=>14,'description'=>'Общий объём','value'=>'440'],
            ['product_id'=>14,'attribute_id'=>53,'description'=>'Объем морозильной камеры','value'=>'115'],
            ['product_id'=>14,'attribute_id'=>26,'description'=>'Количество камер','value'=>'2'],
            ['product_id'=>14,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],
            ['product_id'=>14,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'Plasmacluster'],
            ['product_id'=>14,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'235'],
            ['product_id'=>14,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A++'],
            ['product_id'=>14,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Япония'],
            ['product_id'=>14,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'37'],
            ['product_id'=>14,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>14,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Низкий'],
            ['product_id'=>14,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>14,'attribute_id'=>6,'description'=>'Высота','value'=>'183'],
            ['product_id'=>14,'attribute_id'=>116,'description'=>'Ширина','value'=>'70'],
            ['product_id'=>14,'attribute_id'=>8,'description'=>'Глубина','value'=>'68'],
            ['product_id'=>14,'attribute_id'=>4,'description'=>'Вес','value'=>'75'],

            // Siemens HyperFresh
            ['product_id'=>15,'attribute_id'=>14,'description'=>'Общий объём','value'=>'460'],
            ['product_id'=>15,'attribute_id'=>53,'description'=>'Объем морозильной камеры','value'=>'130'],
            ['product_id'=>15,'attribute_id'=>26,'description'=>'Количество камер','value'=>'3'],
            ['product_id'=>15,'attribute_id'=>16,'description'=>'Зона свежести','value'=>'Да'],
            ['product_id'=>15,'attribute_id'=>98,'description'=>'Тип охлаждения','value'=>'HyperFresh'],
            ['product_id'=>15,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'245'],
            ['product_id'=>15,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A++'],
            ['product_id'=>15,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Германия'],
            ['product_id'=>15,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'36'],
            ['product_id'=>15,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>15,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Низкий'],
            ['product_id'=>15,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>15,'attribute_id'=>6,'description'=>'Высота','value'=>'187'],
            ['product_id'=>15,'attribute_id'=>116,'description'=>'Ширина','value'=>'72'],
            ['product_id'=>15,'attribute_id'=>8,'description'=>'Глубина','value'=>'70'],
            ['product_id'=>15,'attribute_id'=>4,'description'=>'Вес','value'=>'80'],

            // LG TurboWash
            ['product_id'=>16,'attribute_id'=>94,'description'=>'Тип стиральной машины','value'=>'Фронтальная'],
            ['product_id'=>16,'attribute_id'=>15,'description'=>'Загрузка белья','value'=>'8'],
            ['product_id'=>16,'attribute_id'=>75,'description'=>'Скорость отжима','value'=>'1400'],
            ['product_id'=>16,'attribute_id'=>30,'description'=>'Количество программ','value'=>'14'],
            ['product_id'=>16,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A+++'],
            ['product_id'=>16,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'180'],
            ['product_id'=>16,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Корея'],
            ['product_id'=>16,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'52'],
            ['product_id'=>16,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>16,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Низкий'],
            ['product_id'=>16,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>16,'attribute_id'=>6,'description'=>'Высота','value'=>'85'],
            ['product_id'=>16,'attribute_id'=>116,'description'=>'Ширина','value'=>'60'],
            ['product_id'=>16,'attribute_id'=>8,'description'=>'Глубина','value'=>'55'],
            ['product_id'=>16,'attribute_id'=>4,'description'=>'Вес','value'=>'70'],

            // Samsung EcoBubble
            ['product_id'=>17,'attribute_id'=>94,'description'=>'Тип стиральной машины','value'=>'Фронтальная'],
            ['product_id'=>17,'attribute_id'=>15,'description'=>'Загрузка белья','value'=>'9'],
            ['product_id'=>17,'attribute_id'=>75,'description'=>'Скорость отжима','value'=>'1200'],
            ['product_id'=>17,'attribute_id'=>30,'description'=>'Количество программ','value'=>'12'],
            ['product_id'=>17,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A++'],
            ['product_id'=>17,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'190'],
            ['product_id'=>17,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Корея'],
            ['product_id'=>17,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'54'],
            ['product_id'=>17,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>17,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Средний'],
            ['product_id'=>17,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>17,'attribute_id'=>6,'description'=>'Высота','value'=>'85'],
            ['product_id'=>17,'attribute_id'=>116,'description'=>'Ширина','value'=>'60'],
            ['product_id'=>17,'attribute_id'=>8,'description'=>'Глубина','value'=>'56'],
            ['product_id'=>17,'attribute_id'=>4,'description'=>'Вес','value'=>'72'],

            // Bosch Serie 6
            ['product_id'=>18,'attribute_id'=>94,'description'=>'Тип стиральной машины','value'=>'Фронтальная'],
            ['product_id'=>18,'attribute_id'=>15,'description'=>'Загрузка белья','value'=>'7'],
            ['product_id'=>18,'attribute_id'=>75,'description'=>'Скорость отжима','value'=>'1400'],
            ['product_id'=>18,'attribute_id'=>30,'description'=>'Количество программ','value'=>'15'],
            ['product_id'=>18,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A+++'],
            ['product_id'=>18,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'170'],
            ['product_id'=>18,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Германия'],
            ['product_id'=>18,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'50'],
            ['product_id'=>18,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>18,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Низкий'],
            ['product_id'=>18,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>18,'attribute_id'=>6,'description'=>'Высота','value'=>'85'],
            ['product_id'=>18,'attribute_id'=>116,'description'=>'Ширина','value'=>'60'],
            ['product_id'=>18,'attribute_id'=>8,'description'=>'Глубина','value'=>'55'],
            ['product_id'=>18,'attribute_id'=>4,'description'=>'Вес','value'=>'68'],

            // Whirlpool FreshCare+
            ['product_id'=>19,'attribute_id'=>94,'description'=>'Тип стиральной машины','value'=>'Фронтальная'],
            ['product_id'=>19,'attribute_id'=>15,'description'=>'Загрузка белья','value'=>'8'],
            ['product_id'=>19,'attribute_id'=>75,'description'=>'Скорость отжима','value'=>'1200'],
            ['product_id'=>19,'attribute_id'=>30,'description'=>'Количество программ','value'=>'13'],
            ['product_id'=>19,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A++'],
            ['product_id'=>19,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'185'],
            ['product_id'=>19,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Италия'],
            ['product_id'=>19,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'53'],
            ['product_id'=>19,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>19,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Средний'],
            ['product_id'=>19,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>19,'attribute_id'=>6,'description'=>'Высота','value'=>'85'],
            ['product_id'=>19,'attribute_id'=>116,'description'=>'Ширина','value'=>'60'],
            ['product_id'=>19,'attribute_id'=>8,'description'=>'Глубина','value'=>'57'],
            ['product_id'=>19,'attribute_id'=>4,'description'=>'Вес','value'=>'73'],

            // Electrolux PerfectCare
            ['product_id'=>20,'attribute_id'=>94,'description'=>'Тип стиральной машины','value'=>'Фронтальная'],
            ['product_id'=>20,'attribute_id'=>15,'description'=>'Загрузка белья','value'=>'9'],
            ['product_id'=>20,'attribute_id'=>75,'description'=>'Скорость отжима','value'=>'1400'],
            ['product_id'=>20,'attribute_id'=>30,'description'=>'Количество программ','value'=>'16'],
            ['product_id'=>20,'attribute_id'=>21,'description'=>'Класс энергоэффективности','value'=>'A+++'],
            ['product_id'=>20,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'175'],
            ['product_id'=>20,'attribute_id'=>80,'description'=>'Страна производства','value'=>'Швеция'],
            ['product_id'=>20,'attribute_id'=>105,'description'=>'Уровень шума','value'=>'51'],
            ['product_id'=>20,'attribute_id'=>17,'description'=>'Инверторный двигатель','value'=>'Да'],
            ['product_id'=>20,'attribute_id'=>104,'description'=>'Уровень вибрации','value'=>'Низкий'],
            ['product_id'=>20,'attribute_id'=>41,'description'=>'Материал корпуса','value'=>'Металл'],
            ['product_id'=>20,'attribute_id'=>6,'description'=>'Высота','value'=>'85'],
            ['product_id'=>20,'attribute_id'=>116,'description'=>'Ширина','value'=>'60'],
            ['product_id'=>20,'attribute_id'=>8,'description'=>'Глубина','value'=>'56'],
            ['product_id'=>20,'attribute_id'=>4,'description'=>'Вес','value'=>'71'],

            // Samsung Galaxy S23
            ['product_id'=>21,'attribute_id'=>70,'description'=>'Разрешение экрана','value'=>'2340x1080'],
            ['product_id'=>21,'attribute_id'=>12,'description'=>'Диагональ экрана','value'=>'6.1'],
            ['product_id'=>21,'attribute_id'=>56,'description'=>'Объем RAM','value'=>'8'],
            ['product_id'=>21,'attribute_id'=>54,'description'=>'Объем накопителя','value'=>'256'],
            ['product_id'=>21,'attribute_id'=>82,'description'=>'Тип аккумулятора','value'=>'Li-Ion'],
            ['product_id'=>21,'attribute_id'=>109,'description'=>'Частота памяти GPU','value'=>'3200'],
            ['product_id'=>21,'attribute_id'=>4,'description'=>'Вес','value'=>'168'],
            ['product_id'=>21,'attribute_id'=>112,'description'=>'Цвет','value'=>'Черный'],
            ['product_id'=>21,'attribute_id'=>112,'description'=>'Цвет','value'=>'Белый'],
            ['product_id'=>21,'attribute_id'=>112,'description'=>'Цвет','value'=>'Зеленый'],

            // Samsung Galaxy S23 Ultra
            ['product_id'=>22,'attribute_id'=>70,'description'=>'Разрешение экрана','value'=>'3088x1440'],
            ['product_id'=>22,'attribute_id'=>12,'description'=>'Диагональ экрана','value'=>'6.8'],
            ['product_id'=>22,'attribute_id'=>56,'description'=>'Объем RAM','value'=>'12'],
            ['product_id'=>22,'attribute_id'=>54,'description'=>'Объем накопителя','value'=>'512'],
            ['product_id'=>22,'attribute_id'=>82,'description'=>'Тип аккумулятора','value'=>'Li-Ion'],
            ['product_id'=>22,'attribute_id'=>4,'description'=>'Вес','value'=>'234'],
            ['product_id'=>22,'attribute_id'=>112,'description'=>'Цвет','value'=>'Черный'],
            ['product_id'=>22,'attribute_id'=>112,'description'=>'Цвет','value'=>'Красный'],
            ['product_id'=>22,'attribute_id'=>112,'description'=>'Цвет','value'=>'Золотой'],

            // Samsung Galaxy Z Flip5
            ['product_id'=>23,'attribute_id'=>70,'description'=>'Разрешение экрана','value'=>'2640x1080'],
            ['product_id'=>23,'attribute_id'=>12,'description'=>'Диагональ экрана','value'=>'6.7'],
            ['product_id'=>23,'attribute_id'=>56,'description'=>'Объем RAM','value'=>'8'],
            ['product_id'=>23,'attribute_id'=>54,'description'=>'Объем накопителя','value'=>'256'],
            ['product_id'=>23,'attribute_id'=>82,'description'=>'Тип аккумулятора','value'=>'Li-Po'],
            ['product_id'=>23,'attribute_id'=>4,'description'=>'Вес','value'=>'187'],
            ['product_id'=>23,'attribute_id'=>112,'description'=>'Цвет','value'=>'Фиолетовый'],
            ['product_id'=>23,'attribute_id'=>112,'description'=>'Цвет','value'=>'Черный'],
            ['product_id'=>23,'attribute_id'=>112,'description'=>'Цвет','value'=>'Серебристый'],

            // Samsung Galaxy Z Fold5
            ['product_id'=>24,'attribute_id'=>70,'description'=>'Разрешение экрана','value'=>'2176x1812'],
            ['product_id'=>24,'attribute_id'=>12,'description'=>'Диагональ экрана','value'=>'7.6'],
            ['product_id'=>24,'attribute_id'=>56,'description'=>'Объем RAM','value'=>'12'],
            ['product_id'=>24,'attribute_id'=>54,'description'=>'Объем накопителя','value'=>'512'],
            ['product_id'=>24,'attribute_id'=>82,'description'=>'Тип аккумулятора','value'=>'Li-Po'],
            ['product_id'=>24,'attribute_id'=>4,'description'=>'Вес','value'=>'253'],
            ['product_id'=>24,'attribute_id'=>112,'description'=>'Цвет','value'=>'Черный'],
            ['product_id'=>24,'attribute_id'=>112,'description'=>'Цвет','value'=>'Синий'],
            ['product_id'=>24,'attribute_id'=>112,'description'=>'Цвет','value'=>'Золотой'],

            // Samsung Galaxy A54
            ['product_id'=>25,'attribute_id'=>70,'description'=>'Разрешение экрана','value'=>'2400x1080'],
            ['product_id'=>25,'attribute_id'=>12,'description'=>'Диагональ экрана','value'=>'6.4'],
            ['product_id'=>25,'attribute_id'=>56,'description'=>'Объем RAM','value'=>'6'],
            ['product_id'=>25,'attribute_id'=>54,'description'=>'Объем накопителя','value'=>'128'],
            ['product_id'=>25,'attribute_id'=>82,'description'=>'Тип аккумулятора','value'=>'Li-Ion'],
            ['product_id'=>25,'attribute_id'=>4,'description'=>'Вес','value'=>'189'],
            ['product_id'=>25,'attribute_id'=>112,'description'=>'Цвет','value'=>'Белый'],
            ['product_id'=>25,'attribute_id'=>112,'description'=>'Цвет','value'=>'Черный'],
            ['product_id'=>25,'attribute_id'=>112,'description'=>'Цвет','value'=>'Зеленый'],

            ['product_id'=>26,'attribute_id'=>12,'description'=>'Диагональ экрана','value'=>'14'],
            ['product_id'=>26,'attribute_id'=>70,'description'=>'Разрешение экрана','value'=>'2560x1600'],
            ['product_id'=>26,'attribute_id'=>56,'description'=>'Объем RAM','value'=>'16'],
            ['product_id'=>26,'attribute_id'=>54,'description'=>'Объем накопителя','value'=>'512'],
            ['product_id'=>26,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'Intel Core i7-1360P'],
            ['product_id'=>26,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'Intel Iris Xe'],
            ['product_id'=>26,'attribute_id'=>82,'description'=>'Тип аккумулятора','value'=>'Li-Po'],
            ['product_id'=>26,'attribute_id'=>4,'description'=>'Вес','value'=>'1.2'],
            ['product_id'=>26,'attribute_id'=>6,'description'=>'Высота','value'=>'15'],
            ['product_id'=>26,'attribute_id'=>116,'description'=>'Ширина','value'=>'315'],
            ['product_id'=>26,'attribute_id'=>8,'description'=>'Глубина','value'=>'220'],
            ['product_id'=>26,'attribute_id'=>112,'description'=>'Цвет','value'=>'Черный'],
            ['product_id'=>26,'attribute_id'=>112,'description'=>'Цвет','value'=>'Серый'],

            ['product_id'=>27,'attribute_id'=>12,'description'=>'Диагональ экрана','value'=>'14'],
            ['product_id'=>27,'attribute_id'=>70,'description'=>'Разрешение экрана','value'=>'1920x1080'],
            ['product_id'=>27,'attribute_id'=>56,'description'=>'Объем RAM','value'=>'8'],
            ['product_id'=>27,'attribute_id'=>54,'description'=>'Объем накопителя','value'=>'256'],
            ['product_id'=>27,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'AMD Ryzen 5 7530U'],
            ['product_id'=>27,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'AMD Radeon Graphics'],
            ['product_id'=>27,'attribute_id'=>82,'description'=>'Тип аккумулятора','value'=>'Li-Ion'],
            ['product_id'=>27,'attribute_id'=>4,'description'=>'Вес','value'=>'1.4'],
            ['product_id'=>27,'attribute_id'=>6,'description'=>'Высота','value'=>'16'],
            ['product_id'=>27,'attribute_id'=>116,'description'=>'Ширина','value'=>'320'],
            ['product_id'=>27,'attribute_id'=>8,'description'=>'Глубина','value'=>'215'],
            ['product_id'=>27,'attribute_id'=>112,'description'=>'Цвет','value'=>'Серебристый'],
            ['product_id'=>27,'attribute_id'=>112,'description'=>'Цвет','value'=>'Фиолетовый'],

            ['product_id'=>28,'attribute_id'=>12,'description'=>'Диагональ экрана','value'=>'16'],
            ['product_id'=>28,'attribute_id'=>70,'description'=>'Разрешение экрана','value'=>'2560x1600'],
            ['product_id'=>28,'attribute_id'=>56,'description'=>'Объем RAM','value'=>'32'],
            ['product_id'=>28,'attribute_id'=>54,'description'=>'Объем накопителя','value'=>'1024'],
            ['product_id'=>28,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'AMD Ryzen 7 7840H'],
            ['product_id'=>28,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'NVIDIA GeForce RTX 4070'],
            ['product_id'=>28,'attribute_id'=>82,'description'=>'Тип аккумулятора','value'=>'Li-Ion'],
            ['product_id'=>28,'attribute_id'=>4,'description'=>'Вес','value'=>'2.5'],
            ['product_id'=>28,'attribute_id'=>6,'description'=>'Высота','value'=>'26'],
            ['product_id'=>28,'attribute_id'=>116,'description'=>'Ширина','value'=>'360'],
            ['product_id'=>28,'attribute_id'=>8,'description'=>'Глубина','value'=>'260'],
            ['product_id'=>28,'attribute_id'=>112,'description'=>'Цвет','value'=>'Черный'],
            ['product_id'=>28,'attribute_id'=>112,'description'=>'Цвет','value'=>'Белый'],

            ['product_id'=>29,'attribute_id'=>12,'description'=>'Диагональ экрана','value'=>'15.6'],
            ['product_id'=>29,'attribute_id'=>70,'description'=>'Разрешение экрана','value'=>'1920x1080'],
            ['product_id'=>29,'attribute_id'=>56,'description'=>'Объем RAM','value'=>'8'],
            ['product_id'=>29,'attribute_id'=>54,'description'=>'Объем накопителя','value'=>'256'],
            ['product_id'=>29,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'Intel Core i5-1235U'],
            ['product_id'=>29,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'Intel Iris Xe'],
            ['product_id'=>29,'attribute_id'=>82,'description'=>'Тип аккумулятора','value'=>'Li-Ion'],
            ['product_id'=>29,'attribute_id'=>4,'description'=>'Вес','value'=>'1.7'],
            ['product_id'=>29,'attribute_id'=>6,'description'=>'Высота','value'=>'19'],
            ['product_id'=>29,'attribute_id'=>116,'description'=>'Ширина','value'=>'360'],
            ['product_id'=>29,'attribute_id'=>8,'description'=>'Глубина','value'=>'240'],
            ['product_id'=>29,'attribute_id'=>112,'description'=>'Цвет','value'=>'Серый'],
            ['product_id'=>29,'attribute_id'=>112,'description'=>'Цвет','value'=>'Синий'],

            ['product_id'=>30,'attribute_id'=>12,'description'=>'Диагональ экрана','value'=>'14'],
            ['product_id'=>30,'attribute_id'=>70,'description'=>'Разрешение экрана','value'=>'1920x1080'],
            ['product_id'=>30,'attribute_id'=>56,'description'=>'Объем RAM','value'=>'16'],
            ['product_id'=>30,'attribute_id'=>54,'description'=>'Объем накопителя','value'=>'512'],
            ['product_id'=>30,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'Intel Core i7-1255U'],
            ['product_id'=>30,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'Intel Iris Xe'],
            ['product_id'=>30,'attribute_id'=>82,'description'=>'Тип аккумулятора','value'=>'Li-Po'],
            ['product_id'=>30,'attribute_id'=>4,'description'=>'Вес','value'=>'1.5'],
            ['product_id'=>30,'attribute_id'=>6,'description'=>'Высота','value'=>'17'],
            ['product_id'=>30,'attribute_id'=>116,'description'=>'Ширина','value'=>'320'],
            ['product_id'=>30,'attribute_id'=>8,'description'=>'Глубина','value'=>'220'],
            ['product_id'=>30,'attribute_id'=>112,'description'=>'Цвет','value'=>'Черный'],
            ['product_id'=>30,'attribute_id'=>112,'description'=>'Цвет','value'=>'Серебристый'],

            ['product_id'=>31,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'NVIDIA GeForce RTX 4090'],
            ['product_id'=>31,'attribute_id'=>51,'description'=>'Объем видеопамяти','value'=>'24'],
            ['product_id'=>31,'attribute_id'=>84,'description'=>'Тип видеопамяти','value'=>'GDDR6X'],
            ['product_id'=>31,'attribute_id'=>108,'description'=>'Частота GPU','value'=>'2235'],
            ['product_id'=>31,'attribute_id'=>109,'description'=>'Частота памяти GPU','value'=>'21000'],
            ['product_id'=>31,'attribute_id'=>64,'description'=>'Поддержка Ray Tracing','value'=>'Да'],
            ['product_id'=>31,'attribute_id'=>24,'description'=>'Количество вентиляторов GPU','value'=>'3'],
            ['product_id'=>31,'attribute_id'=>4,'description'=>'Вес','value'=>'2.3'],

            ['product_id'=>32,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'NVIDIA GeForce RTX 4080'],
            ['product_id'=>32,'attribute_id'=>51,'description'=>'Объем видеопамяти','value'=>'16'],
            ['product_id'=>32,'attribute_id'=>84,'description'=>'Тип видеопамяти','value'=>'GDDR6X'],
            ['product_id'=>32,'attribute_id'=>108,'description'=>'Частота GPU','value'=>'2205'],
            ['product_id'=>32,'attribute_id'=>109,'description'=>'Частота памяти GPU','value'=>'19000'],
            ['product_id'=>32,'attribute_id'=>64,'description'=>'Поддержка Ray Tracing','value'=>'Да'],
            ['product_id'=>32,'attribute_id'=>24,'description'=>'Количество вентиляторов GPU','value'=>'3'],
            ['product_id'=>32,'attribute_id'=>4,'description'=>'Вес','value'=>'2.0'],

            ['product_id'=>33,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'NVIDIA GeForce RTX 4070 Ti'],
            ['product_id'=>33,'attribute_id'=>51,'description'=>'Объем видеопамяти','value'=>'12'],
            ['product_id'=>33,'attribute_id'=>84,'description'=>'Тип видеопамяти','value'=>'GDDR6X'],
            ['product_id'=>33,'attribute_id'=>108,'description'=>'Частота GPU','value'=>'2310'],
            ['product_id'=>33,'attribute_id'=>109,'description'=>'Частота памяти GPU','value'=>'18000'],
            ['product_id'=>33,'attribute_id'=>64,'description'=>'Поддержка Ray Tracing','value'=>'Да'],
            ['product_id'=>33,'attribute_id'=>24,'description'=>'Количество вентиляторов GPU','value'=>'2'],
            ['product_id'=>33,'attribute_id'=>4,'description'=>'Вес','value'=>'1.5'],

            ['product_id'=>34,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'AMD Radeon RX 7900 XTX'],
            ['product_id'=>34,'attribute_id'=>51,'description'=>'Объем видеопамяти','value'=>'24'],
            ['product_id'=>34,'attribute_id'=>84,'description'=>'Тип видеопамяти','value'=>'GDDR6'],
            ['product_id'=>34,'attribute_id'=>108,'description'=>'Частота GPU','value'=>'2300'],
            ['product_id'=>34,'attribute_id'=>109,'description'=>'Частота памяти GPU','value'=>'20000'],
            ['product_id'=>34,'attribute_id'=>64,'description'=>'Поддержка Ray Tracing','value'=>'Да'],
            ['product_id'=>34,'attribute_id'=>24,'description'=>'Количество вентиляторов GPU','value'=>'3'],
            ['product_id'=>34,'attribute_id'=>4,'description'=>'Вес','value'=>'2.1'],

            ['product_id'=>35,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'AMD Radeon RX 7800 XT'],
            ['product_id'=>35,'attribute_id'=>51,'description'=>'Объем видеопамяти','value'=>'16'],
            ['product_id'=>35,'attribute_id'=>84,'description'=>'Тип видеопамяти','value'=>'GDDR6'],
            ['product_id'=>35,'attribute_id'=>108,'description'=>'Частота GPU','value'=>'2200'],
            ['product_id'=>35,'attribute_id'=>109,'description'=>'Частота памяти GPU','value'=>'19000'],
            ['product_id'=>35,'attribute_id'=>64,'description'=>'Поддержка Ray Tracing','value'=>'Да'],
            ['product_id'=>35,'attribute_id'=>24,'description'=>'Количество вентиляторов GPU','value'=>'3'],
            ['product_id'=>35,'attribute_id'=>4,'description'=>'Вес','value'=>'1.8'],

            ['product_id'=>36,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'NVIDIA GeForce RTX 4090'],
            ['product_id'=>36,'attribute_id'=>51,'description'=>'Объем видеопамяти','value'=>'24'],
            ['product_id'=>36,'attribute_id'=>84,'description'=>'Тип видеопамяти','value'=>'GDDR6X'],
            ['product_id'=>36,'attribute_id'=>108,'description'=>'Частота GPU','value'=>'2235'],
            ['product_id'=>36,'attribute_id'=>109,'description'=>'Частота памяти GPU','value'=>'21000'],
            ['product_id'=>36,'attribute_id'=>64,'description'=>'Поддержка Ray Tracing','value'=>'Да'],
            ['product_id'=>36,'attribute_id'=>24,'description'=>'Количество вентиляторов GPU','value'=>'3'],
            ['product_id'=>36,'attribute_id'=>4,'description'=>'Вес','value'=>'2.4'],

            ['product_id'=>37,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'NVIDIA GeForce RTX 4080'],
            ['product_id'=>37,'attribute_id'=>51,'description'=>'Объем видеопамяти','value'=>'16'],
            ['product_id'=>37,'attribute_id'=>84,'description'=>'Тип видеопамяти','value'=>'GDDR6X'],
            ['product_id'=>37,'attribute_id'=>108,'description'=>'Частота GPU','value'=>'2205'],
            ['product_id'=>37,'attribute_id'=>109,'description'=>'Частота памяти GPU','value'=>'19000'],
            ['product_id'=>37,'attribute_id'=>64,'description'=>'Поддержка Ray Tracing','value'=>'Да'],
            ['product_id'=>37,'attribute_id'=>24,'description'=>'Количество вентиляторов GPU','value'=>'3'],
            ['product_id'=>37,'attribute_id'=>4,'description'=>'Вес','value'=>'2.1'],

            ['product_id'=>38,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'NVIDIA GeForce RTX 4070 Ti'],
            ['product_id'=>38,'attribute_id'=>51,'description'=>'Объем видеопамяти','value'=>'12'],
            ['product_id'=>38,'attribute_id'=>84,'description'=>'Тип видеопамяти','value'=>'GDDR6X'],
            ['product_id'=>38,'attribute_id'=>108,'description'=>'Частота GPU','value'=>'2310'],
            ['product_id'=>38,'attribute_id'=>109,'description'=>'Частота памяти GPU','value'=>'18000'],
            ['product_id'=>38,'attribute_id'=>64,'description'=>'Поддержка Ray Tracing','value'=>'Да'],
            ['product_id'=>38,'attribute_id'=>24,'description'=>'Количество вентиляторов GPU','value'=>'3'],
            ['product_id'=>38,'attribute_id'=>4,'description'=>'Вес','value'=>'1.9'],

            ['product_id'=>39,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'AMD Radeon RX 7900 XTX'],
            ['product_id'=>39,'attribute_id'=>51,'description'=>'Объем видеопамяти','value'=>'24'],
            ['product_id'=>39,'attribute_id'=>84,'description'=>'Тип видеопамяти','value'=>'GDDR6'],
            ['product_id'=>39,'attribute_id'=>108,'description'=>'Частота GPU','value'=>'2300'],
            ['product_id'=>39,'attribute_id'=>109,'description'=>'Частота памяти GPU','value'=>'20000'],
            ['product_id'=>39,'attribute_id'=>64,'description'=>'Поддержка Ray Tracing','value'=>'Да'],
            ['product_id'=>39,'attribute_id'=>24,'description'=>'Количество вентиляторов GPU','value'=>'3'],
            ['product_id'=>39,'attribute_id'=>4,'description'=>'Вес','value'=>'2.2'],

            ['product_id'=>40,'attribute_id'=>44,'description'=>'Модель GPU','value'=>'AMD Radeon RX 7800 XT'],
            ['product_id'=>40,'attribute_id'=>51,'description'=>'Объем видеопамяти','value'=>'16'],
            ['product_id'=>40,'attribute_id'=>84,'description'=>'Тип видеопамяти','value'=>'GDDR6'],
            ['product_id'=>40,'attribute_id'=>108,'description'=>'Частота GPU','value'=>'2200'],
            ['product_id'=>40,'attribute_id'=>109,'description'=>'Частота памяти GPU','value'=>'19000'],
            ['product_id'=>40,'attribute_id'=>64,'description'=>'Поддержка Ray Tracing','value'=>'Да'],
            ['product_id'=>40,'attribute_id'=>24,'description'=>'Количество вентиляторов GPU','value'=>'2'],
            ['product_id'=>40,'attribute_id'=>4,'description'=>'Вес','value'=>'1.6'],

            ['product_id'=>41,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'Intel Core i9-14900K'],
            ['product_id'=>41,'attribute_id'=>77,'description'=>'Сокет CPU','value'=>'LGA1700'],
            ['product_id'=>41,'attribute_id'=>33,'description'=>'Количество ядер','value'=>'24'],
            ['product_id'=>41,'attribute_id'=>31,'description'=>'Количество потоков','value'=>'32'],
            ['product_id'=>41,'attribute_id'=>107,'description'=>'Частота','value'=>'3.2'],
            ['product_id'=>41,'attribute_id'=>101,'description'=>'Turbo частота','value'=>'6.0'],
            ['product_id'=>41,'attribute_id'=>81,'description'=>'Техпроцесс','value'=>'10'],
            ['product_id'=>41,'attribute_id'=>18,'description'=>'Кэш L1','value'=>'192'],
            ['product_id'=>41,'attribute_id'=>19,'description'=>'Кэш L2','value'=>'32'],
            ['product_id'=>41,'attribute_id'=>20,'description'=>'Кэш L3','value'=>'36'],
            ['product_id'=>41,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'125'],
            ['product_id' => 41, 'attribute_id' => 112, 'description' => 'Цвет', 'value' => 'Черный'],
            ['product_id' => 41, 'attribute_id' => 112, 'description' => 'Цвет', 'value' => 'Белый'],
            ['product_id' => 41, 'attribute_id' => 112, 'description' => 'Цвет', 'value' => 'Металик'],
            ['product_id'=>41,'attribute_id'=>80,'description'=>'Страна производства','value'=>'США'],
            ['product_id'=>41,'attribute_id'=>4,'description'=>'Вес','value'=>'0.1'],

            ['product_id'=>42,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'Intel Core i7-14700K'],
            ['product_id'=>42,'attribute_id'=>77,'description'=>'Сокет CPU','value'=>'LGA1700'],
            ['product_id'=>42,'attribute_id'=>33,'description'=>'Количество ядер','value'=>'20'],
            ['product_id'=>42,'attribute_id'=>31,'description'=>'Количество потоков','value'=>'28'],
            ['product_id'=>42,'attribute_id'=>107,'description'=>'Частота','value'=>'3.4'],
            ['product_id'=>42,'attribute_id'=>101,'description'=>'Turbo частота','value'=>'5.6'],
            ['product_id'=>42,'attribute_id'=>81,'description'=>'Техпроцесс','value'=>'10'],
            ['product_id'=>42,'attribute_id'=>18,'description'=>'Кэш L1','value'=>'160'],
            ['product_id'=>42,'attribute_id'=>19,'description'=>'Кэш L2','value'=>'24'],
            ['product_id'=>42,'attribute_id'=>20,'description'=>'Кэш L3','value'=>'30'],
            ['product_id'=>42,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'125'],
            ['product_id'=>42,'attribute_id'=>80,'description'=>'Страна производства','value'=>'США'],
            ['product_id'=>42,'attribute_id'=>4,'description'=>'Вес','value'=>'0.1'],

            ['product_id'=>43,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'Intel Core i5-14600K'],
            ['product_id'=>43,'attribute_id'=>77,'description'=>'Сокет CPU','value'=>'LGA1700'],
            ['product_id'=>43,'attribute_id'=>33,'description'=>'Количество ядер','value'=>'14'],
            ['product_id'=>43,'attribute_id'=>31,'description'=>'Количество потоков','value'=>'20'],
            ['product_id'=>43,'attribute_id'=>107,'description'=>'Частота','value'=>'3.5'],
            ['product_id'=>43,'attribute_id'=>101,'description'=>'Turbo частота','value'=>'5.3'],
            ['product_id'=>43,'attribute_id'=>81,'description'=>'Техпроцесс','value'=>'10'],
            ['product_id'=>43,'attribute_id'=>18,'description'=>'Кэш L1','value'=>'112'],
            ['product_id'=>43,'attribute_id'=>19,'description'=>'Кэш L2','value'=>'16'],
            ['product_id'=>43,'attribute_id'=>20,'description'=>'Кэш L3','value'=>'24'],
            ['product_id'=>43,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'125'],
            ['product_id'=>43,'attribute_id'=>80,'description'=>'Страна производства','value'=>'США'],
            ['product_id'=>43,'attribute_id'=>4,'description'=>'Вес','value'=>'0.1'],

            ['product_id'=>44,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'AMD Ryzen 9 7950X'],
            ['product_id'=>44,'attribute_id'=>77,'description'=>'Сокет CPU','value'=>'AM5'],
            ['product_id'=>44,'attribute_id'=>33,'description'=>'Количество ядер','value'=>'16'],
            ['product_id'=>44,'attribute_id'=>31,'description'=>'Количество потоков','value'=>'32'],
            ['product_id'=>44,'attribute_id'=>107,'description'=>'Частота','value'=>'4.5'],
            ['product_id'=>44,'attribute_id'=>101,'description'=>'Turbo частота','value'=>'5.7'],
            ['product_id'=>44,'attribute_id'=>81,'description'=>'Техпроцесс','value'=>'5'],
            ['product_id'=>44,'attribute_id'=>18,'description'=>'Кэш L1','value'=>'128'],
            ['product_id'=>44,'attribute_id'=>19,'description'=>'Кэш L2','value'=>'16'],
            ['product_id'=>44,'attribute_id'=>20,'description'=>'Кэш L3','value'=>'64'],
            ['product_id'=>44,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'170'],
            ['product_id'=>44,'attribute_id'=>80,'description'=>'Страна производства','value'=>'США'],
            ['product_id'=>44,'attribute_id'=>4,'description'=>'Вес','value'=>'0.1'],

            ['product_id'=>45,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'AMD Ryzen 7 7800X3D'],
            ['product_id'=>45,'attribute_id'=>77,'description'=>'Сокет CPU','value'=>'AM5'],
            ['product_id'=>45,'attribute_id'=>33,'description'=>'Количество ядер','value'=>'8'],
            ['product_id'=>45,'attribute_id'=>31,'description'=>'Количество потоков','value'=>'16'],
            ['product_id'=>45,'attribute_id'=>107,'description'=>'Частота','value'=>'4.2'],
            ['product_id'=>45,'attribute_id'=>101,'description'=>'Turbo частота','value'=>'5.0'],
            ['product_id'=>45,'attribute_id'=>81,'description'=>'Техпроцесс','value'=>'5'],
            ['product_id'=>45,'attribute_id'=>18,'description'=>'Кэш L1','value'=>'64'],
            ['product_id'=>45,'attribute_id'=>19,'description'=>'Кэш L2','value'=>'8'],
            ['product_id'=>45,'attribute_id'=>20,'description'=>'Кэш L3','value'=>'96'],
            ['product_id'=>45,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'120'],
            ['product_id'=>45,'attribute_id'=>80,'description'=>'Страна производства','value'=>'США'],
            ['product_id'=>45,'attribute_id'=>4,'description'=>'Вес','value'=>'0.1'],

            ['product_id'=>46,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'AMD Ryzen 5 7600X'],
            ['product_id'=>46,'attribute_id'=>77,'description'=>'Сокет CPU','value'=>'AM5'],
            ['product_id'=>46,'attribute_id'=>33,'description'=>'Количество ядер','value'=>'6'],
            ['product_id'=>46,'attribute_id'=>31,'description'=>'Количество потоков','value'=>'12'],
            ['product_id'=>46,'attribute_id'=>107,'description'=>'Частота','value'=>'4.7'],
            ['product_id'=>46,'attribute_id'=>101,'description'=>'Turbo частота','value'=>'5.3'],
            ['product_id'=>46,'attribute_id'=>81,'description'=>'Техпроцесс','value'=>'5'],
            ['product_id'=>46,'attribute_id'=>18,'description'=>'Кэш L1','value'=>'64'],
            ['product_id'=>46,'attribute_id'=>19,'description'=>'Кэш L2','value'=>'6'],
            ['product_id'=>46,'attribute_id'=>20,'description'=>'Кэш L3','value'=>'32'],
            ['product_id'=>46,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'105'],
            ['product_id'=>46,'attribute_id'=>80,'description'=>'Страна производства','value'=>'США'],
            ['product_id'=>46,'attribute_id'=>4,'description'=>'Вес','value'=>'0.1'],

            ['product_id'=>47,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'AMD Ryzen 3 5300G'],
            ['product_id'=>47,'attribute_id'=>77,'description'=>'Сокет CPU','value'=>'AM4'],
            ['product_id'=>47,'attribute_id'=>33,'description'=>'Количество ядер','value'=>'4'],
            ['product_id'=>47,'attribute_id'=>31,'description'=>'Количество потоков','value'=>'8'],
            ['product_id'=>47,'attribute_id'=>107,'description'=>'Частота','value'=>'4.0'],
            ['product_id'=>47,'attribute_id'=>101,'description'=>'Turbo частота','value'=>'4.2'],
            ['product_id'=>47,'attribute_id'=>81,'description'=>'Техпроцесс','value'=>'7'],
            ['product_id'=>47,'attribute_id'=>18,'description'=>'Кэш L1','value'=>'32'],
            ['product_id'=>47,'attribute_id'=>19,'description'=>'Кэш L2','value'=>'2'],
            ['product_id'=>47,'attribute_id'=>20,'description'=>'Кэш L3','value'=>'8'],
            ['product_id'=>47,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'65'],
            ['product_id'=>47,'attribute_id'=>80,'description'=>'Страна производства','value'=>'США'],
            ['product_id'=>47,'attribute_id'=>4,'description'=>'Вес','value'=>'0.1'],

            ['product_id'=>48,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'Intel Core i3-14100'],
            ['product_id'=>48,'attribute_id'=>77,'description'=>'Сокет CPU','value'=>'LGA1700'],
            ['product_id'=>48,'attribute_id'=>33,'description'=>'Количество ядер','value'=>'4'],
            ['product_id'=>48,'attribute_id'=>31,'description'=>'Количество потоков','value'=>'8'],
            ['product_id'=>48,'attribute_id'=>107,'description'=>'Частота','value'=>'3.5'],
            ['product_id'=>48,'attribute_id'=>101,'description'=>'Turbo частота','value'=>'4.4'],
            ['product_id'=>48,'attribute_id'=>81,'description'=>'Техпроцесс','value'=>'10'],
            ['product_id'=>48,'attribute_id'=>18,'description'=>'Кэш L1','value'=>'32'],
            ['product_id'=>48,'attribute_id'=>19,'description'=>'Кэш L2','value'=>'4'],
            ['product_id'=>48,'attribute_id'=>20,'description'=>'Кэш L3','value'=>'12'],
            ['product_id'=>48,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'65'],
            ['product_id'=>48,'attribute_id'=>80,'description'=>'Страна производства','value'=>'США'],
            ['product_id'=>48,'attribute_id'=>4,'description'=>'Вес','value'=>'0.1'],

            ['product_id'=>49,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'Intel Xeon W-3495X'],
            ['product_id'=>49,'attribute_id'=>77,'description'=>'Сокет CPU','value'=>'LGA4677'],
            ['product_id'=>49,'attribute_id'=>33,'description'=>'Количество ядер','value'=>'56'],
            ['product_id'=>49,'attribute_id'=>31,'description'=>'Количество потоков','value'=>'112'],
            ['product_id'=>49,'attribute_id'=>107,'description'=>'Частота','value'=>'1.9'],
            ['product_id'=>49,'attribute_id'=>101,'description'=>'Turbo частота','value'=>'4.8'],
            ['product_id'=>49,'attribute_id'=>81,'description'=>'Техпроцесс','value'=>'10'],
            ['product_id'=>49,'attribute_id'=>18,'description'=>'Кэш L1','value'=>'448'],
            ['product_id'=>49,'attribute_id'=>19,'description'=>'Кэш L2','value'=>'112'],
            ['product_id'=>49,'attribute_id'=>20,'description'=>'Кэш L3','value'=>'105'],
            ['product_id'=>49,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'350'],
            ['product_id'=>49,'attribute_id'=>80,'description'=>'Страна производства','value'=>'США'],
            ['product_id'=>49,'attribute_id'=>4,'description'=>'Вес','value'=>'0.2'],

            ['product_id'=>50,'attribute_id'=>45,'description'=>'Модель процессора','value'=>'AMD EPYC 9654'],
            ['product_id'=>50,'attribute_id'=>77,'description'=>'Сокет CPU','value'=>'SP5'],
            ['product_id'=>50,'attribute_id'=>33,'description'=>'Количество ядер','value'=>'96'],
            ['product_id'=>50,'attribute_id'=>31,'description'=>'Количество потоков','value'=>'192'],
            ['product_id'=>50,'attribute_id'=>107,'description'=>'Частота','value'=>'2.4'],
            ['product_id'=>50,'attribute_id'=>101,'description'=>'Turbo частота','value'=>'3.7'],
            ['product_id'=>50,'attribute_id'=>81,'description'=>'Техпроцесс','value'=>'5'],
            ['product_id'=>50,'attribute_id'=>18,'description'=>'Кэш L1','value'=>'768'],
            ['product_id'=>50,'attribute_id'=>19,'description'=>'Кэш L2','value'=>'192'],
            ['product_id'=>50,'attribute_id'=>20,'description'=>'Кэш L3','value'=>'384'],
            ['product_id'=>50,'attribute_id'=>117,'description'=>'Энергопотребление','value'=>'360'],
            ['product_id'=>50,'attribute_id'=>80,'description'=>'Страна производства','value'=>'США'],
            ['product_id'=>50,'attribute_id'=>4,'description'=>'Вес','value'=>'0.3']

        ])->into('product_attributes')->exec();
    }

    public function down()
    {
        DB::query("DELETE FROM categories WHERE id > 1");
    }
}
